package ORM;
// Generated 8 nov. 2021 7:27:15 by Hibernate Tools 5.5.7.Final

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private String dni;
	private Departamento departamento;
	private String nomEmp;
	private Empleadodatosprof empleadodatosprof;

	public Empleado() {
	}

	public Empleado(String dni, Departamento departamento, String nomEmp) {
		this.dni = dni;
		this.departamento = departamento;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, Departamento departamento, String nomEmp, Empleadodatosprof empleadodatosprof) {
		this.dni = dni;
		this.departamento = departamento;
		this.nomEmp = nomEmp;
		this.empleadodatosprof = empleadodatosprof;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public Empleadodatosprof getEmpleadodatosprof() {
		return this.empleadodatosprof;
	}

	public void setEmpleadodatosprof(Empleadodatosprof empleadodatosprof) {
		this.empleadodatosprof = empleadodatosprof;
	}

}
