package ORM;
// Generated 8 nov. 2021 7:27:15 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Proyectosede generated by hbm2java
 */
public class Proyectosede implements java.io.Serializable {

	private ProyectosedeId id;
	private Proyecto proyecto;
	private Sede sede;
	private Date finicio;
	private Date ffin;

	public Proyectosede() {
	}

	public Proyectosede(ProyectosedeId id, Proyecto proyecto, Sede sede, Date finicio) {
		this.id = id;
		this.proyecto = proyecto;
		this.sede = sede;
		this.finicio = finicio;
	}

	public Proyectosede(ProyectosedeId id, Proyecto proyecto, Sede sede, Date finicio, Date ffin) {
		this.id = id;
		this.proyecto = proyecto;
		this.sede = sede;
		this.finicio = finicio;
		this.ffin = ffin;
	}

	public ProyectosedeId getId() {
		return this.id;
	}

	public void setId(ProyectosedeId id) {
		this.id = id;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public Date getFinicio() {
		return this.finicio;
	}

	public void setFinicio(Date finicio) {
		this.finicio = finicio;
	}

	public Date getFfin() {
		return this.ffin;
	}

	public void setFfin(Date ffin) {
		this.ffin = ffin;
	}

}
