package ORM;
// Generated 8 nov. 2021 7:27:15 by Hibernate Tools 5.5.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private Date finicio;
	private Date ffin;
	private String nomProy;
	private Set proyectosedes = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(Date finicio, String nomProy) {
		this.finicio = finicio;
		this.nomProy = nomProy;
	}

	public Proyecto(Date finicio, Date ffin, String nomProy, Set proyectosedes) {
		this.finicio = finicio;
		this.ffin = ffin;
		this.nomProy = nomProy;
		this.proyectosedes = proyectosedes;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public Date getFinicio() {
		return this.finicio;
	}

	public void setFinicio(Date finicio) {
		this.finicio = finicio;
	}

	public Date getFfin() {
		return this.ffin;
	}

	public void setFfin(Date ffin) {
		this.ffin = ffin;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Set getProyectosedes() {
		return this.proyectosedes;
	}

	public void setProyectosedes(Set proyectosedes) {
		this.proyectosedes = proyectosedes;
	}

}
