package ORM;
// Generated 8 nov. 2021 7:27:15 by Hibernate Tools 5.5.7.Final

/**
 * ProyectosedeId generated by hbm2java
 */
public class ProyectosedeId implements java.io.Serializable {

	private int idProy;
	private int idSede;

	public ProyectosedeId() {
	}

	public ProyectosedeId(int idProy, int idSede) {
		this.idProy = idProy;
		this.idSede = idSede;
	}

	public int getIdProy() {
		return this.idProy;
	}

	public void setIdProy(int idProy) {
		this.idProy = idProy;
	}

	public int getIdSede() {
		return this.idSede;
	}

	public void setIdSede(int idSede) {
		this.idSede = idSede;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectosedeId))
			return false;
		ProyectosedeId castOther = (ProyectosedeId) other;

		return (this.getIdProy() == castOther.getIdProy()) && (this.getIdSede() == castOther.getIdSede());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProy();
		result = 37 * result + this.getIdSede();
		return result;
	}

}
