package ORM;
// Generated 8 nov. 2021 7:27:15 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede implements java.io.Serializable {

	private Integer idSede;
	private String nomSede;
	private Set departamentos = new HashSet(0);
	private Set proyectosedes = new HashSet(0);

	public Sede() {
	}

	public Sede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Sede(String nomSede, Set departamentos, Set proyectosedes) {
		this.nomSede = nomSede;
		this.departamentos = departamentos;
		this.proyectosedes = proyectosedes;
	}

	public Integer getIdSede() {
		return this.idSede;
	}

	public void setIdSede(Integer idSede) {
		this.idSede = idSede;
	}

	public String getNomSede() {
		return this.nomSede;
	}

	public void setNomSede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Set getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set departamentos) {
		this.departamentos = departamentos;
	}

	public Set getProyectosedes() {
		return this.proyectosedes;
	}

	public void setProyectosedes(Set proyectosedes) {
		this.proyectosedes = proyectosedes;
	}

}
